language: python
dist: trusty

python:
  - "2.7"

sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

virtualenv:
  system_site_packages: true

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip install selenium notebook

script:
  - python test.py
